### ISSUE TITLE
Add environment variable as stage variable

### ISSUE THREAD

**Issue by RobQuistNL** [bsander/jsonmerger#4]
Maybe its useful to add an environment variable (together with the hostname matching).

This way you can easiliy spoof certain configs on different machines, and won't need to update the project if you want to run, say an extra server with the same config.

Also useful for using local development / virtualbox development / acceptance servers / automated testing servers.

**Comment by thabemmz** [comment]
Closing this was implemented in https://github.com/bsander/jsonmerger/pull/8
